FROM python:3.11-slim
WORKDIR /app

COPY requirements-streamlit.txt .
RUN pip3 install -r requirements-streamlit.txt

COPY app.py .
COPY sql/ sql/
COPY etl/ etl/

EXPOSE 8501

CMD streamlit run app.py --server.address 0.0.0.0 --server.port 8501